- DEVICE_IP: 10.105.58.120:9001
  PIPELINE_NAME: p001
  PIPELINE_TEMPLATE: test_pipeline_template.json
  DATA_SOURCE_FILE: test_data_source.json
  DATA_LOGIC_FILE: test_data_logic.json
  DATA_TARGET_FILE: test_data_target.json
  DATA_VARIABLES_FILE: test_data_vars.json
- DEVICE_IP: 10.105.58.120:9002
  PIPELINE_NAME: p002
  DATA_SOURCE_FILE: test_data_source.json
  DATA_TARGET_FILE: test_data_target.json
  DATA_VARIABLES_FILE: test_data_vars.json
